; Atlantis DeepSea - BIP85 Password Manager
; Target: LilyGO T-Display (ESP32 + 1.14" ST7789 LCD)

[env:lilygo-t-display]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -DBOARD_HAS_PSRAM
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER
    -DTFT_WIDTH=135
    -DTFT_HEIGHT=240
    -DTFT_MOSI=19
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=16
    -DTFT_RST=23
    -DTFT_BL=4
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_FONT6
    -DLOAD_FONT7
    -DLOAD_FONT8
    -DLOAD_GFXFF
    -DSMOOTH_FONT
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=20000000
    -O2

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
